export const ASSETS = {
  LOGOS: {
    HORIZONTAL: '/images/logos/Logo-horizontal-sf.webp',
    SIMPLE: '/images/logos/logo-simple.webp',
  },
  MEGA_MENU: {
    GALAPAGOS: '/images/mega-menu/galapagos.webp',
    AMAZONIA: '/images/mega-menu/amazonia.webp',
    ANDES_CULTURA: '/images/mega-menu/andes-cultura.webp',
    ANDES_NATURALEZA: '/images/mega-menu/andes-naturaleza.webp',
    COSTA: '/images/mega-menu/costa.webp',
    CRUCEROS: '/images/mega-menu/cruceros.webp',
    CIRCUITOS: '/images/mega-menu/circuitos.webp',
    DAY_TOURS: '/images/mega-menu/day-tours.webp',
    BIRDWATCHING: '/images/mega-menu/birdwatching.webp',
    GALLERY_FAUNA: '/images/mega-menu/gallery-fauna.webp',
    GALLERY_PAISAJES: '/images/mega-menu/gallery-paisajes.webp',
    GALLERY_CULTURA: '/images/mega-menu/gallery-cultura.webp',
    GALLERY_AVENTURA: '/images/mega-menu/gallery-aventura.webp',
  },
  GALLERY: {
    GALAPAGOS: '/images/galapagos.webp',
    AMAZONIA: '/images/amazonia.webp',
    ANDES_NATURALEZA: '/images/andes-naturaleza.webp',
    PAISAJE: '/images/paisaje.webp',
    LOBITOS: '/images/lobitos.webp',
    GALAPAGOS_CASTILLOS: '/images/galapagos/Castillos y Lobos Española.webp',
    GALAPAGOS_DSC_0436: '/images/galapagos/DSC_0436.webp',
    GALAPAGOS_TORTUGA: '/images/galapagos/GLP 5 Amalia con TortugaMarina Mayo2019.webp',
    GALAPAGOS_SEA_LIONS: '/images/galapagos/GLP Children sea Lions and sandcastles.webp',
    GALAPAGOS_FLYCATCHER: '/images/galapagos/Galapagos Flycatcher y Luis 2.webp',
    GALAPAGOS_PORTADA: '/images/galapagos/galapagos.webp',
    AMAZONIA_BUHO: '/images/amazonia/Buho Crestado 01.webp',
    AMAZONIA_NUTRIA: '/images/amazonia/Nutria Gigante 02 LDD Sacha Lodge.webp',
    AMAZONIA_PASARELA: '/images/amazonia/SachaLodge 13 Pasarela Ag2019.webp',
    AMAZONIA_CANAL: '/images/amazonia/SachaLodge 14 Canal Ag2019.webp',
    AMAZONIA_VIAJE_15: '/images/amazonia/Viaje Ecuador 15 Sacha Ag2024 .webp',
    AMAZONIA_VIAJE_22: '/images/amazonia/Viaje Ecuador 22 Sacha Ag2024 .webp',
    // Pendiente: subir fotos reales a estas carpetas (ver frontend/public/images/andes-cultura/.gitkeep
    // y frontend/public/images/andes-naturaleza/.gitkeep). Nombres de archivo esperados abajo.
    ANDES_CULTURA_01: '/images/andes-cultura/andes-cultura-01.webp',
    ANDES_CULTURA_02: '/images/andes-cultura/andes-cultura-02.webp',
    ANDES_CULTURA_03: '/images/andes-cultura/andes-cultura-03.webp',
    ANDES_NATURALEZA_01: '/images/andes-naturaleza/andes-naturaleza-01.webp',
    ANDES_NATURALEZA_02: '/images/andes-naturaleza/andes-naturaleza-02.webp',
    ANDES_NATURALEZA_03: '/images/andes-naturaleza/andes-naturaleza-03.webp',
  },
  HERO: {
    COMPUTER: {
      DSC_0436: '/images/hero-main/computer/DSC_0436.webp',
      TORTUGA_MARINA: '/images/hero-main/computer/GLP 5 Amalia con TortugaMarina Mayo2019.webp',
      SEA_LIONS: '/images/hero-main/computer/GLP Children sea Lions and sandcastles.webp',
      ORCAS: '/images/hero-main/computer/Orcas Mom and Calf Feb2016.webp',
      PAPALLACTA: '/images/hero-main/computer/Papallacta Die-Muriel 2 Oct2016.webp',
      COCK_OF_THE_ROCK: '/images/hero-main/computer/Reserva PazdelasAves Cock-of-the-Rock Nov2018.webp',
      SACHA_LODGE: '/images/hero-main/computer/SachaLodge 29 Barizo Ag2019.webp',
      VIAJE_ECUADOR: '/images/hero-main/computer/Viaje Ecuador 22 Sacha Ag2024.webp',
      YUBARTA: '/images/hero-main/computer/Yubarta 8 Isla de La Plata Ag2019.webp',
      LOBITOS: '/images/hero-main/computer/lobitos.webp',
      PIQUERO: '/images/hero-main/computer/piquero.webp',
      PAISAJE: '/images/hero-main/computer/paisaje.webp',
    },
    MOBILE: {
      PAPALLACTA_ANTISANA: '/images/hero-main/mobile/Papallacta Antisana Nov2016.webp',
      LOBITO: '/images/hero-main/mobile/lobito.webp',
      PIQUEROS: '/images/hero-main/mobile/piqueros.webp',
    },
  },
  SVG: {
    ECUADOR_HIGH: '/ecuadorHigh.svg',
    SOUTH_AMERICA_LOW: '/southAmericaLow.svg',
  },
} as const
