export const ROUTES = {
  HOME: '/',
  DESTINATIONS: '/destinations',
  DESTINATION: (slug: string) => `/destinations/${slug}`,
  EXPERIENCES: '/experiences',
  EXPERIENCE: (slug: string) => `/experiences/${slug}`,
  GALLERY: '/gallery',
  GALLERY_CATEGORY: (category: string) => `/gallery?category=${category}`,
  GALLERY_FILTERED: (category: string, sub: string) => `/gallery?category=${category}&sub=${sub}`,
  ABOUT: '/about',
  CONTACT: '/contact',
  TOURS: '/tours',
  TOUR: (id: string) => `/tours/${id}`,
  TOUR_CONTACT: (id: string) => `/contact?tour=${id}`,
} as const
